# environment with pandas, numpy, matplotlib, scikit-learn, maad
name: bambird2

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9.7  # Python 3.9 was widely used around December 2021
  - pandas=1.3.5
  - numpy=1.21.4
  - matplotlib=3.5.0
  - scikit-learn=1.0.1
  - ipykernel=6.6.0
  - pyyaml=6.0
  - pip=21.3.1
  - librosa=0.8.1
  - kneed=0.7.0
  - tqdm=4.62.3
  - hdbscan=0.8.27
  - umap-learn=0.5.2
  - scipy=1.7.3
  - joblib=1.1.0  # Ensure a compatible version of joblib
  - pip:
    - scikit-maad==1.3.12
    - scipy==1.7.3
    - numpy==1.21.4
